name: Build & release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.NOSTALGIK_RELEASE_PAT }}
      - name: Prepare repo
        run: git fetch --unshallow --tags
      - name: Setup Node Config
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # Skip post-install scripts as malicious script could steal any token
      - name: Run yarn install
        run: yarn install --ignore-scripts --frozen-lockfile
      - name: Auto release
        env:
          GITHUB_TOKEN: ${{ secrets.NOSTALGIK_RELEASE_PAT }}
        run: yarn auto shipit
